{% set name = "xopt" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a492d3f13f841940e44113974bbc685d123750ca8d402e147a2ffbb6079546ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch >=0.9.2,<=0.10.0
    - gpytorch
    - pandas
    - pydantic >=2.3
    - orjson
    - matplotlib

test:
  imports:
    - xopt
  requires:
    - pytest
    - mpi4py
    - dask
    - openssh
  source_files:
    - xopt/tests
  commands:
    - pytest xopt/tests

about:
  home: https://github.com/xopt-org/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
