{% set name = "xopt" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e24fd2497b6ccbb1ac8d6f24670f91513f21228b7c0756571907074647d1b543

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pyyaml
    - deap

test:
  imports:
    - xopt

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Accelerator optimization, based on DEAP
  description: |
    Accelerator optimization, based on DEAP

extra:
  recipe-maintainers:
    - ChristopherMayes
