{% set name = "xopt" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 7f1bc0015bfe8d6245a2d42f9d03b06f7f81a5563471f834380b42ce32b33757

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch
    - gpytorch
    - pandas
    - ipywidgets
    - tqdm

test:
  imports:
    - xopt

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: Apache-2.0 
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
