{% set name = "xopt" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ChristopherMayes/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9870c0bf1b636b32944e19fb10895bedc82cdd20733be6c0d1b788ded3e890fb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - pyyaml
    - deap
    - pytorch
    - botorch
    - gpytorch
    - pandas
    - ipywidgets
    - tqdm
    - pydantic

test:
  imports:
    - xopt

about:
  home: https://github.com/ChristopherMayes/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible optimization of arbitrary problems in Python.
  description: |
    Flexible optimization of arbitrary problems in Python.

extra:
  recipe-maintainers:
    - ChristopherMayes
